### ISSUE TITLE
Documentation fix

### ISSUE THREAD

**Issue by nBhati** [cescoffier/vertx-microservices-workshop#44]
INSTALL.md just mentions to copy parent pom to repository which doesn't install the pom and hence build of other module fails.

Please add below to documentation 

mvn install:install-file -Dpackaging=pom -Dfile=~/.m2/repository/io/vertx/workshop/vertx-microservice-workshop/1.0-SNAPSHOT/vertx-microservice-workshop-1.0-SNAPSHOT.pom.xml -DpomFile=~/.m2/repository/io/vertx/workshop/vertx-microservice-workshop/1.0-SNAPSHOT/vertx-microservice-workshop-1.0-SNAPSHOT.pom.xml

**Comment by cescoffier** [comment]
Did you try with mvn install -N ?

**Comment by nBhati** [comment]
I tried mvn install -N but it didnt work. i had to manually install the parent pom in repository.

Thanks

**Comment by cescoffier** [comment]
odd, because that's exactly what `mvn -N install` is doing (installing the root pom).
Anyway, can you open a PR?

**Comment by nBhati** [comment]
Hi @cescoffier,

I tried `mvn -N install` after removing dir path for parent pom and it worked. i have updated documentation as needed and raised PR.

Thanks
