### ISSUE TITLE
Enhance and add Chain.java to vertx core

### ISSUE THREAD

**Issue by cazacugmihai** [cescoffier/vertx-microservices-workshop#9]
Hi,

Can you extract [Chain.java](https://github.com/cescoffier/vertx-microservices-workshop/blob/0f34db195d55082fe27582dcf04aeaebb9b916a0/vertx-workshop-common/src/main/java/io/vertx/workshop/common/Chain.java)'s methods into io.vertx.core.CompositeFuture? It is a very common way to run sequential features and I think that many of us use a kind of the same utility class (instead of writing something like [Sequential composition](http://vertx.io/docs/vertx-core/java/#_sequential_composition)).

Thanks,
Mihai

**Comment by cescoffier** [comment]
Hi @cazacugmihai 

Please open a "wish" on https://github.com/vert-x3/issues/issues and track it from there. (don't forget to vote with a +1 on your issue)

**Comment by cazacugmihai** [comment]
Done. https://github.com/vert-x3/issues/issues/192
